version: '3.6'
services:
  app:
    container_name: kummerkasten
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./app:/kummerkasten/app
      - ./prisma:/kummerkasten/prisma
      - ./utils:/kummerkasten/utils
    command: sh run.sh
