const DEFAULTS = {
  MAX_CONTENT_LENGTH: 1028,
  MAX_TITLE_LENGTH: 32,
  MIN_CONTENT_LENGTH: 16,
  MIN_TITLE_LENGTH: 4,
  REPORTS_TO_HIDE_POST: 3,
  DATE_LOCALE: 'de-DE',
};

export default DEFAULTS;
