name: Test

on:
  pull_request:
    branches:
      - main

env:
  UNLOCK_PASSWORD: test
  DELETE_PASSWORD: test

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright
        run: |
          npx playwright install --with-deps
          npx playwright install-deps

      - name: Build Project
        run: npm run build

      - name: Prepare Database
        run: npm run prepare:db

      - name: Run Server
        run: |
          UNLOCK_PASSWORD=${{ env.UNLOCK_PASSWORD }} \
          DELETE_PASSWORD=${{ env.DELETE_PASSWORD } \
          npm start &

      - name: Wait for Server
        run: sleep 10

      - name: Run Tests
        run: |
          UNLOCK_PASSWORD=${{ env.UNLOCK_PASSWORD }} \
          DELETE_PASSWORD=${{ env.DELETE_PASSWORD } \
          npm run tests

      - name: Stop Server
        run: kill -9 $(lsof -t -i:3000)
